#include <stdlib.h>
#include <iostream>

#include "snark.hpp"

using namespace libsnark;
using namespace std;

int main()
{
    default_r1cs_ppzksnark_pp::init_public_params();
    auto keypair = generate_keypair<default_r1cs_ppzksnark_pp>();

    std::vector<bool> h1 = {false, false, false, false, true, true, true, false, true, true, false, true, false, false, true, true, true, false, false, false, true, true, false, true, false, false, false, false, true, true, true, false, false, true, false, true, false, true, true, true, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, true, true, false, true, true, true, false, true, true, false, true, false, false, true, true, true, true, false, true, true, true, false, true, false, true, true, true, true, true, false, false, true, true, false, false, true, false, true, true, true, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, false, false, true, true, false, false, true, true, true, false, true, false, false, false, false, false, true, true, true, false, false, true, true, true, true, false, false, false, true, false, true, false, true, false, true, false, true, false, true, false, true, true, true, true, false, false, false, false, true, true, false, false, true, true, false, true, true, true, true, false, true, false, false, true, false, true, true, false, true, false, true, true, true, false, false, false, true, true, true, true, true, true, false, false, false, true, true, false, true, false, true, false, true, false, false, true, false, false, false, true, false, false, false, false, true, true, true, true, true, false, false, false, true, false, false, false, false, false, true, false, true, true, true, true, true, false, false, true, true, false, true, true, false, false, true, true, true};
    std::vector<bool> h2 = {false, true, false, false, false, false, false, true, false, true, false, false, false, true, false, true, false, true, false, true, false, false, true, false, true, false, false, false, false, false, true, false, true, true, false, true, false, true, true, false, true, true, true, true, true, false, true, false, true, true, true, false, true, false, true, true, false, false, false, false, true, false, true, true, false, false, false, false, false, false, true, false, true, false, true, true, true, false, true, true, false, true, true, false, false, true, false, false, false, true, false, false, false, false, false, true, true, false, false, true, false, false, true, false, false, true, false, false, true, true, true, false, false, false, false, false, false, true, true, true, true, false, true, false, false, false, false, false, false, false, true, false, true, false, true, true, false, true, false, true, true, false, true, true, true, false, false, false, true, true, false, true, false, false, true, true, false, false, false, true, true, true, false, false, true, false, false, false, false, true, false, false, true, false, false, false, true, false, true, true, false, false, true, true, true, false, true, false, false, true, false, false, true, true, true, true, false, false, true, false, false, false, false, true, true, false, false, false, true, false, false, true, true, true, true, false, false, false, false, true, false, true, false, true, true, true, true, false, true, true, false, true, false, true, true, true, true, true, true, false, true, false, false, true, false, true, true, false, true, false, false, false, true, false, false, true};
    std::vector<bool> x = {false, true, true, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, true, false, true, false, true, true, true, false, false, false, true, false, false, false, true, false, true, false, true, true, true, false, false, true, true, false, false, true, true, false, false, false, true, false, false, false, false, true, true, false, false, false, false, true, true, false, true, true, true, true, false, false, true, true, true, false, false, false, true, true, true, false, true, true, false, false, true, false, true, false, false, false, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true, false, true, true, true, false, true, true, false, false, false, false, false, true, true, false, true, true, true, true, true, false, false, true, true, true, false, true, false, true, true, false, false, false, true, false, true, false, false, false, true, false, false, false, false, true, false, false, true, true, true, true, false, false, true, false, false, false, false, true, true, false, true, true, false, false, true, false, false, true, false, false, true, true, true, true, false, false, false, false, false, false, false, true, true, true, false, true, true, false, true, true, false, true, true, false, true, true, true, true, true, false, true, false, false, true, true, true, true, true, false, true, false, true, false, true, false, true, true, false, false, false, true, true, false, false, false, false, false, true, false, false, false, true, true, true, false, false, false, true, true, true, false, true, false, true, false, false, true, false};
    std::vector<bool> r1 = {false, true, true, true, true, false, true, true, false, true, true, true, true, true, true, true, false, false, true, true, false, true, false, false, false, true, true, true, true, false, true, false, false, true, true, true, true, false, true, false, false, false, false, false, true, true, true, false, true, false, false, true, false, false, false, true, true, true, true, true, true, false, false, true, false, true, false, true, true, false, true, true, true, true, false, true, false, false, false, true, true, false, true, true, false, true, false, true, false, false, false, false, true, false, true, false, false, true, true, true, false, true, true, true, false, false, true, false, false, true, true, true, true, false, true, false, true, false, true, false, true, false, false, false, true, false, false, false, true, false, true, true, false, true, true, false, false, true, false, true, true, false, true, false, false, false, true, true, true, true, false, true, true, true, false, true, false, false, false, true, false, true, true, true, false, false, false, true, false, false, false, false, false, false, true, true, true, false, false, true, true, true, true, true, false, false, true, true, false, true, false, true, false, true, false, true, true, false, false, false, false, false, true, false, false, false, true, true, true, true, true, true, false, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, true, true, true, false, true, false, false, false, true, true, true, true, false, true, true, false, true, true, true, false, true, false, false, false, true, true, false};
    std::vector<bool> r2 = {false, false, false, true, true, false, true, true, false, true, false, false, true, true, true, true, false, false, false, false, true, true, true, false, true, false, false, true, true, false, false, false, false, true, false, true, false, false, false, true, true, false, false, true, false, true, true, true, false, false, false, true, true, false, false, true, true, false, false, true, true, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, false, false, true, false, false, false, false, false, false, true, true, true, true, false, false, false, false, true, false, true, false, true, false, false, false, true, false, false, true, true, false, false, true, false, false, true, false, true, true, false, true, false, true, true, false, false, true, true, false, true, true, false, true, true, false, false, false, false, true, true, true, true, false, true, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, true, true, false, true, true, true, true, true, false, true, true, true, true, true, false, false, true, false, true, false, true, false, true, false, false, false, true, true, false, false, true, true, false, false, true, false, false, false, true, true, false, true, false, true, true, false, false, true, true, true, false, true, false, true, true, false, true, true, true, true, false, false, false, true, true, true, false, true, true, false, false, false, false, false, true, true, false, true, false, true, false, true, true, false, false, true, true, true, false, false, false, false, false, false, false, true, false, true, false, false};

    auto proof = generate_proof<default_r1cs_ppzksnark_pp>(keypair.pk, h1, h2, x, r1, r2);

    assert(verify_proof(keypair.vk, proof, h1, h2, x));
}